export const ERROR_CODES = {
    PROCESS_FAILURE_ERROR: 'process_failure_error',
    USER_ALREADY_EXISTS: 'user_already_exists',
    VALIDATION_ERROR: 'validation_error',
    INVALID_CREDENTIALS: 'invalid_credentials',
    INACTIVE_USER: 'inactive_user',
    AUTHORIZATION_ERROR: 'authorization_error',
    MARKDOWN_ALREADY_EXISTS: 'markdown_already_exists',
    MARKDOWN_NOT_FOUND: 'markdown_not_found',
    MARKDOWN_ID_NOT_FOUND: 'markdown_id_not_found',
    MARKDOWN_NOTE_ID_NOT_FOUND: 'markdown_note_id_not_found',
    MARKDOWN_NOTE_NOT_FOUND: 'markdown_note_not_found',
    FILE_SIZE_EXCEEDED: 'file_size_exceeded',
    FILE_TYPE_INVALID: 'file_type_invalid',
    MARKDOWN_PHOTO_FILE_COUNT_EXCEEDED: 'markdown_photo_file_count_exceeded',
    MARKDOWN_PHOTO_NOT_FOUND: 'markdown_photo_not_found',
    CURRENT_AND_NEW_PASSWORD_CANNOT_BE_EQUAL:
        'current_and_new_password_cannot_be_equal',
    MARKDOWN_PHOTO_ID_NOT_FOUND: 'markdown_photo_id_not_found',
    NOT_FOUND: 'not_found',
    USER_NOT_FOUND: 'user_not_found',
    RESET_PASSWORD_TOKEN_NOT_FOUND: 'reset_password_token_not_found',
    RESET_PASSWORD_TOKEN_EXPIRED: 'reset_password_token_expired',
    TOO_MANY_RESET_PASSWORD_REQUESTS: 'too_many_reset_password_requests',
};

export const ERROR_MESSAGES = {
    process_failure_error: 'Process failure error.',
    user_already_exists: 'User already exists.',
    validation_error: 'Validation error.',
    invalid_credentials: 'Invalid credentials.',
    inactive_user: 'Inactive user.',
    authorization_error: 'Authorization error.',
    markdown_already_exists:
        'Markdown with the same geo-location already exists.',
    markdown_not_found: 'Markdown not found.',
    markdown_id_not_found: 'Markdown id not found.',
    markdown_note_id_not_found: 'Markdown note id not found.',
    markdown_note_not_found: 'Markdown note not found.',
    file_size_exceeded: 'File size exceeded.',
    file_type_invalid: 'File type invalid.',
    markdown_photo_file_count_exceeded: 'Markdown photo file count exceeded.',
    markdown_photo_not_found: 'Markdown photo not found.',
    current_and_new_password_cannot_be_equal:
        'Current and new password can not be equal.',
    markdown_photo_id_not_found: 'Markdown photo id not found.',
    not_found: 'Not found.',
    user_not_found: 'User not found.',
    reset_password_token_not_found: 'Reset password token not found.',
    reset_password_token_expired: 'Reset password token expired.',
    too_many_reset_password_requests:
        'You have made too many reset password requests. Please try again later.',
};
