export const ERROR_CODES = {
    processFailureError: 'process_failure_error',
    userAlreadyExists: 'user_already_exists',
    validationError: 'validation_error',
    invalidCredentials: 'invalid_credentials',
    inactiveUser: 'inactive_user',
    authorizationError: 'authorization_error',
    markdownAlreadyExists: 'markdown_already_exists',
    markdownNotFound: 'markdown_not_found',
    markdownIdNotFound: 'markdown_id_not_found',
    markdownNoteIdNotFound: 'markdown_note_id_not_found',
    markdownNoteNotFound: 'markdown_note_not_found',
    fileSizeExceeded: 'file_size_exceeded',
    fileTypeInvalid: 'file_type_invalid',
    markdownPhotoFileCountExceeded: 'markdown_photo_file_count_exceeded',
    markdownPhotoNotFound: 'markdown_photo_not_found',
};

export const ERROR_MESSAGES = {
    process_failure_error: 'Process failure error.',
    user_already_exists: 'User already exists.',
    validation_error: 'Validation error.',
    invalid_credentials: 'Invalid credentials.',
    inactive_user: 'Inactive user.',
    authorization_error: 'Authorization error.',
    markdown_already_exists:
        'Markdown with the same geo-location already exists.',
    markdown_not_found: 'Markdown not found.',
    markdown_id_not_found: 'Markdown id not found.',
    markdown_note_id_not_found: 'Markdown note id not found.',
    markdown_note_not_found: 'Markdown note not found.',
    file_size_exceeded: 'File size exceeded.',
    file_type_invalid: 'File type invalid.',
    markdown_photo_file_count_exceeded: 'Markdown photo file count exceeded.',
    markdown_photo_not_found: 'Markdown photo not found.',
};
